"""cambio a 3 roles admin profesor alumno

Revision ID: 8f666d84673e
Revises: d3a32bc3d56b
Create Date: 2026-06-29 18:06:53.959436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f666d84673e'
down_revision: Union[str, Sequence[str], None] = 'd3a32bc3d56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role AS ENUM ('ADMIN', 'TEACHER', 'STUDENT')")
    
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'TEACHER', 'STUDENT', name='role'), nullable=True))
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'role')
    
    op.execute("DROP TYPE role")
    # ### end Alembic commands ###
