"""add is_active and is_superuser to users

Revision ID: d3a32bc3d56b
Revises: fb7fb803b1f8
Create Date: 2026-06-29 17:46:18.603711

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd3a32bc3d56b'
down_revision: Union[str, Sequence[str], None] = 'fb7fb803b1f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
